return {
  { "tpope/vim-repeat" },
  { "bronson/vim-visual-star-search" },
  { "farmergreg/vim-lastplace" },
  { "lervag/file-line" },
  { "romgrk/barbar.nvim" },
  { "sindrets/diffview.nvim" },
  { "numToStr/Comment.nvim", event = 'VeryLazy' },
  { 'kylechui/nvim-surround', config = true, event = 'VeryLazy' },
  { 'nvim-lualine/lualine.nvim', config = true, event = 'VeryLazy' },
  { "mg979/vim-visual-multi", event = 'VeryLazy' },
  { 'MagicDuck/grug-far.nvim', cmd = 'GrugFar', config = true },
  { 'nguyenvukhang/nvim-toggler', event = 'VeryLazy', config = true },
  { 'chentoast/marks.nvim', event = 'VeryLazy', config = true },
  { "mfussenegger/nvim-dap", event = 'VeryLazy' },
  { "suketa/nvim-dap-ruby", event = 'VeryLazy', config = true },
}
