return {
  { "tpope/vim-repeat" },
  { "tpope/vim-unimpaired" },
  { "numToStr/Comment.nvim" },
  { "bronson/vim-visual-star-search" },
  { "farmergreg/vim-lastplace" },
  { "lervag/file-line" },
  { "nvim-tree/nvim-web-devicons" },
  { "romgrk/barbar.nvim" },
  { "nvim-lua/plenary.nvim" },
  { "MunifTanjim/nui.nvim" },
  { "ludovicchabant/vim-gutentags" },
  { "mbbill/undotree" },
  { "sindrets/diffview.nvim" },
  { "mg979/vim-visual-multi" },
  { 'MagicDuck/grug-far.nvim', config = true },
  { 'kylechui/nvim-surround', config = true },
  { 'nguyenvukhang/nvim-toggler', config = true },
}
